export const UPDATE_ITEM = Symbol('UPDATE_ITEM')
export const ADD_ITEM = Symbol('ADD_ITEM')
export const REMOVE_ITEM = Symbol('REMOVE_ITEM')
export const LIST_ITEM = Symbol('LIST_ITEM')
export const SEARCH = Symbol('SEARCH')
